version: '3'

services:
  db:
    container_name: db
    restart: always
    build:
      context: ./db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_TEST_DATABASE=${DATABASE_TEST_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    depends_on:
      - db
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
      - API_ENTRYPOINT_SCHEME=${API_ENTRYPOINT_SCHEME}
      - API_ENTRYPOINT_HOST=${API_ENTRYPOINT_HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    volumes:
      - ../app:/var/app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../app:/var/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=mwl-elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_HOST}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOST}
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

#  logstash:
#    container_name: logstash
#    image: docker.elastic.co/logstash/logstash:7.8.1
#    ports:
#      - "5044:5044"
#    volumes:
#      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro

volumes:
  es_data:
    driver: local
  db_data:
    name: ${DB_VOLUME_NAME}
