version: '3'

services:
  db:
    container_name: db
    restart: always
    build:
      context: ./db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_TEST_DATABASE=${DATABASE_TEST_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
      args:
        - XDEBUG_ENABLED=${XDEBUG_ENABLED}
    depends_on:
      - db
    environment:
      - XDEBUG_CONFIG=${XDEBUG_CONFIG}
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:3306/${DATABASE_NAME}
      - API_ENTRYPOINT_SCHEME=${API_ENTRYPOINT_SCHEME}
      - API_ENTRYPOINT_HOST=${API_ENTRYPOINT_HOST}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS}
      - CORS_ALLOW_ORIGIN=${CORS_ALLOW_ORIGIN}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    volumes:
      - ../app:/var/app

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ../app:/var/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:5-alpine
    ports:
      - "9200:9200"

volumes:
  db_data:
    name: ${DB_VOLUME_NAME}
