admin_basket:
    path: /admin/basket/{basketId}
    defaults:
        _controller: app.controller.basket:getBasket
    methods: [GET]

admin_baskets:
    path: /admin/basket
    defaults:
        _controller: app.controller.basket:getBaskets
    methods: [GET]
